// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("Men's Casual Shoes Category", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder()
      .forBrowser("chrome")
      .usingServer("http://localhost:4444/wd/hub")
      .build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout);
    const handlesThen = vars["windowHandles"];
    const handlesNow = await driver.getAllWindowHandles();
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find((handle) => !handlesThen.includes(handle));
    }
    throw new Error("New window did not appear before timeout");
  }
  it("Men's Casual Shoes Category", async function () {
    // Test name: Men's Casual Shoes Category
    // Step # | name | target | value
    // 1 | open | / |
    await driver.get("https://www.google.com/");
    // 2 | setWindowSize | 1728x1079 |
    await driver.manage().window().setRect({ width: 1728, height: 1079 });
    // 3 | click | id=APjFqb |
    await driver.findElement(By.id("APjFqb")).click();
    // 4 | type | id=APjFqb | google india
    await driver.findElement(By.id("APjFqb")).sendKeys("google india");
    // 5 | click | css=.eKjLze .LC20lb |
    await driver.findElement(By.css(".eKjLze .LC20lb")).click();
    // 6 | type | id=APjFqb | casual shoes in india
    await driver.findElement(By.id("APjFqb")).sendKeys("casual shoes in india");
    // 7 | runScript | window.scrollTo(0,312) |
    await driver.executeScript("window.scrollTo(0,312)");
    // 8 | click | css=.g:nth-child(12) .LC20lb |
    await driver.findElement(By.css(".g:nth-child(12) .LC20lb")).click();
    // 9 | click | css=.r2CdBx:nth-child(4) > .R0cyWM |
    await driver.findElement(By.css(".r2CdBx:nth-child(4) > .R0cyWM")).click();
    // 10 | mouseOver | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(2) > .\\_75nlfW > div:nth-child(1) .gqcSqV")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 11 | mouseOut | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 12 | runScript | window.scrollTo(0,6978) |
    await driver.executeScript("window.scrollTo(0,6978)");
    // 13 | click | css=.r2CdBx:nth-child(4) > .R0cyWM |
    await driver.findElement(By.css(".r2CdBx:nth-child(4) > .R0cyWM")).click();
    // 14 | mouseOver | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(2) > .\\_75nlfW > div:nth-child(1) .gqcSqV")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 15 | mouseOut | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 16 | mouseOver | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(2) > .\\_75nlfW > div:nth-child(1) .gqcSqV")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 17 | mouseOut | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 18 | mouseOver | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(2) > .\\_75nlfW > div:nth-child(1) .gqcSqV")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 19 | mouseOut | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 20 | mouseOver | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(2) > .\\_75nlfW > div:nth-child(1) .gqcSqV")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 21 | mouseOut | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 22 | mouseOver | css=.cPHDOP:nth-child(2) div:nth-child(2) .\_53J4C-:nth-child(1) |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(2) div:nth-child(2) .\\_53J4C-:nth-child(1)")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 23 | mouseOut | css=.cPHDOP:nth-child(2) div:nth-child(2) .\_53J4C-:nth-child(1) |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 24 | runScript | window.scrollTo(0,0) |
    await driver.executeScript("window.scrollTo(0,0)");
    // 25 | mouseOver | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(2) > .\\_75nlfW > div:nth-child(1) .gqcSqV")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 26 | mouseOut | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .gqcSqV |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 27 | runScript | window.scrollTo(0,646) |
    await driver.executeScript("window.scrollTo(0,646)");
    // 28 | click | css=.\-5qqlC:nth-child(11) .ewzVkT:nth-child(2) .XqNaEv |
    await driver
      .findElement(
        By.css(".\\-5qqlC:nth-child(11) .ewzVkT:nth-child(2) .XqNaEv")
      )
      .click();
    // 29 | mouseOver | css=.cPHDOP:nth-child(2) div:nth-child(2) .gqcSqV |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(2) div:nth-child(2) .gqcSqV")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 30 | mouseOut | css=.cPHDOP:nth-child(2) div:nth-child(2) .gqcSqV |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 31 | runScript | window.scrollTo(0,219) |
    await driver.executeScript("window.scrollTo(0,219)");
    // 32 | runScript | window.scrollTo(0,689) |
    await driver.executeScript("window.scrollTo(0,689)");
    // 33 | runScript | window.scrollTo(0,1159) |
    await driver.executeScript("window.scrollTo(0,1159)");
    // 34 | click | css=.Cd8ZYz .\_53J4C- |
    vars["windowHandles"] = await driver.getAllWindowHandles();
    // 35 | storeWindowHandle | root |
    await driver.findElement(By.css(".Cd8ZYz .\\_53J4C-")).click();
    // 36 | selectWindow | handle=${win5748} |
    vars["win5748"] = await waitForWindow(2000);
    // 37 | click | css=.HDvrBb > .Wphh3N > span |
    vars["root"] = await driver.getWindowHandle();
    // 38 | click | css=.\_6n9Uuq |
    await driver.switchTo().window(vars["win5748"]);
    // 39 | click | css=.col-4-12 |
    await driver.findElement(By.css(".HDvrBb > .Wphh3N > span")).click();
    // 40 | click | css=.sXu3Qz |
    await driver.findElement(By.css(".\\_6n9Uuq")).click();
    // 41 | click | css=.sXu3Qz |
    await driver.findElement(By.css(".col-4-12")).click();
    // 42 | click | css=.sXu3Qz |
    await driver.findElement(By.css(".sXu3Qz")).click();
    // 43 | click | css=.HDvrBb > .Wphh3N > span |
    await driver.findElement(By.css(".sXu3Qz")).click();
    // 44 | click | css=.HDvrBb > .Wphh3N > span |
    await driver.findElement(By.css(".sXu3Qz")).click();
    // 45 | runScript | window.scrollTo(0,1781) |
    await driver.findElement(By.css(".HDvrBb > .Wphh3N > span")).click();
    // 46 | runScript | window.scrollTo(0,1587) |
    await driver.findElement(By.css(".HDvrBb > .Wphh3N > span")).click();
    // 47 | click | css=.rYpYQA |
    await driver.executeScript("window.scrollTo(0,1781)");
    // 48 | click | css=.row:nth-child(1) > .col-3-12 |
    await driver.executeScript("window.scrollTo(0,1587)");
    // 49 | click | css=.row:nth-child(2) > .col-3-12 |
    await driver.findElement(By.css(".rYpYQA")).click();
    // 50 | click | css=.row:nth-child(3) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(1) > .col-3-12")).click();
    // 51 | click | css=.row:nth-child(4) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(2) > .col-3-12")).click();
    // 52 | click | css=.row:nth-child(5) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(3) > .col-3-12")).click();
    // 53 | click | css=.row:nth-child(6) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(4) > .col-3-12")).click();
    // 54 | click | css=.t7DWYS |
    await driver.findElement(By.css(".row:nth-child(5) > .col-3-12")).click();
    // 55 | click | css=.ELSIVL:nth-child(2) > .Ez0xjR |
    await driver.findElement(By.css(".row:nth-child(6) > .col-3-12")).click();
    // 56 | click | css=.ELSIVL:nth-child(2) > .xe2C75 |
    await driver.findElement(By.css(".t7DWYS")).click();
    // 57 | click | css=.ELSIVL:nth-child(2) > .xe2C75 |
    await driver.findElement(By.css(".ELSIVL:nth-child(2) > .Ez0xjR")).click();
    // 58 | click | css=.YFFHum:nth-child(2) > .col |
    await driver.findElement(By.css(".ELSIVL:nth-child(2) > .xe2C75")).click();
    // 59 | click | css=.row:nth-child(2) > .col > .S3CJ7s |
    await driver.findElement(By.css(".ELSIVL:nth-child(2) > .xe2C75")).click();
    // 60 | click | css=.gtm1So |
    await driver.findElement(By.css(".YFFHum:nth-child(2) > .col")).click();
    // 61 | close |  |
    await driver
      .findElement(By.css(".row:nth-child(2) > .col > .S3CJ7s"))
      .click();
    // 62 | selectWindow | handle=${root} |
    await driver.findElement(By.css(".gtm1So")).click();
    // 63 | mouseOver | css=.cPHDOP:nth-child(4) div:nth-child(2) .\_53J4C-:nth-child(1) |
    await driver.close();
    // 64 | mouseOut | css=.cPHDOP:nth-child(4) div:nth-child(2) .\_53J4C-:nth-child(1) |
    await driver.switchTo().window(vars["root"]);
    // 65 | mouseOver | css=.cPHDOP:nth-child(6) div:nth-child(2) .gqcSqV |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(4) div:nth-child(2) .\\_53J4C-:nth-child(1)")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 66 | mouseOut | css=.cPHDOP:nth-child(6) div:nth-child(2) .gqcSqV |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 67 | click | css=.cPHDOP:nth-child(7) div:nth-child(3) .\_53J4C-:nth-child(1) |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(6) div:nth-child(2) .gqcSqV")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 68 | selectWindow | handle=${win8163} |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body");
      await driver
        .actions({ bridge: true })
        .moveToElement(element, 0, 0)
        .perform();
    }
    // 69 | selectWindow | handle=${root} |
    vars["windowHandles"] = await driver.getAllWindowHandles();
    // 70 | mouseOver | css=.cPHDOP:nth-child(7) div:nth-child(3) .\_53J4C-:nth-child(1) |
    await driver
      .findElement(
        By.css(".cPHDOP:nth-child(7) div:nth-child(3) .\\_53J4C-:nth-child(1)")
      )
      .click();
    // 71 | selectWindow | handle=${win4460} |
    vars["win8163"] = await waitForWindow(2000);
    // 72 | close |  |
    vars["windowHandles"] = await driver.getAllWindowHandles();
    // 73 | selectWindow | handle=${win8163} |
    await driver.switchTo().window(vars["win8163"]);
    // 74 | click | css=.Nx9bqj |
    vars["win4460"] = await waitForWindow(2000);
    // 75 | click | css=.Nx9bqj |
    await driver.switchTo().window(vars["root"]);
    // 76 | doubleClick | css=.Nx9bqj |
    {
      const element = await driver.findElement(
        By.css(".cPHDOP:nth-child(7) div:nth-child(3) .\\_53J4C-:nth-child(1)")
      );
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    // 77 | click | css=.VU-ZEz |
    await driver.switchTo().window(vars["win4460"]);
    // 78 | click | css=.VU-ZEz |
    await driver.close();
    // 79 | doubleClick | css=.VU-ZEz |
    await driver.switchTo().window(vars["win8163"]);
    // 80 | click | css=.mEh187 |
    await driver.findElement(By.css(".Nx9bqj")).click();
    // 81 | click | css=.mEh187 |
    await driver.findElement(By.css(".Nx9bqj")).click();
    // 82 | doubleClick | css=.mEh187 |
    {
      const element = await driver.findElement(By.css(".Nx9bqj"));
      await driver.actions({ bridge: true }).doubleClick(element).perform();
    }
    // 83 | click | css=.HDvrBb > .Wphh3N > span |
    await driver.findElement(By.css(".VU-ZEz")).click();
    // 84 | click | css=.HDvrBb > .Wphh3N > span |
    await driver.findElement(By.css(".VU-ZEz")).click();
    // 85 | click | css=.\_6n9Uuq |
    {
      const element = await driver.findElement(By.css(".VU-ZEz"));
      await driver.actions({ bridge: true }).doubleClick(element).perform();
    }
    // 86 | click | css=.E3wXvA |
    await driver.findElement(By.css(".mEh187")).click();
    // 87 | click | css=.E3wXvA |
    await driver.findElement(By.css(".mEh187")).click();
    // 88 | doubleClick | css=.E3wXvA |
    {
      const element = await driver.findElement(By.css(".mEh187"));
      await driver.actions({ bridge: true }).doubleClick(element).perform();
    }
    // 89 | click | css=.atZ055 > span |
    await driver.findElement(By.css(".HDvrBb > .Wphh3N > span")).click();
    // 90 | click | css=.atZ055 > span |
    await driver.findElement(By.css(".HDvrBb > .Wphh3N > span")).click();
    // 91 | doubleClick | css=.atZ055 > span |
    await driver.findElement(By.css(".\\_6n9Uuq")).click();
    // 92 | click | css=.atZ055 > span |
    await driver.findElement(By.css(".E3wXvA")).click();
    // 93 | click | css=.atZ055 > span |
    await driver.findElement(By.css(".E3wXvA")).click();
    // 94 | doubleClick | css=.atZ055 > span |
    {
      const element = await driver.findElement(By.css(".E3wXvA"));
      await driver.actions({ bridge: true }).doubleClick(element).perform();
    }
    // 95 | click | css=.HDvrBb > .Wphh3N > span |
    await driver.findElement(By.css(".atZ055 > span")).click();
    // 96 | click | css=.rYpYQA |
    await driver.findElement(By.css(".atZ055 > span")).click();
    // 97 | click | css=.n4gy8q |
    {
      const element = await driver.findElement(By.css(".atZ055 > span"));
      await driver.actions({ bridge: true }).doubleClick(element).perform();
    }
    // 98 | click | css=.row:nth-child(1) > .col-9-12 |
    await driver.findElement(By.css(".atZ055 > span")).click();
    // 99 | click | css=.row:nth-child(1) > .col-3-12 |
    await driver.findElement(By.css(".atZ055 > span")).click();
    // 100 | click | css=.row:nth-child(2) > .col-3-12 |
    {
      const element = await driver.findElement(By.css(".atZ055 > span"));
      await driver.actions({ bridge: true }).doubleClick(element).perform();
    }
    // 101 | click | css=.row:nth-child(2) > .col-9-12 |
    await driver.findElement(By.css(".HDvrBb > .Wphh3N > span")).click();
    // 102 | click | css=.row:nth-child(3) > .col-3-12 |
    await driver.findElement(By.css(".rYpYQA")).click();
    // 103 | click | css=.row:nth-child(3) > .col-9-12 |
    await driver.findElement(By.css(".n4gy8q")).click();
    // 104 | click | css=.row:nth-child(4) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(1) > .col-9-12")).click();
    // 105 | click | css=.row:nth-child(4) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(1) > .col-3-12")).click();
    // 106 | click | css=.row:nth-child(5) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(2) > .col-3-12")).click();
    // 107 | click | css=.row:nth-child(5) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(2) > .col-9-12")).click();
    // 108 | click | css=.row:nth-child(6) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(3) > .col-3-12")).click();
    // 109 | click | css=.row:nth-child(6) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(3) > .col-9-12")).click();
    // 110 | click | css=.row:nth-child(7) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(4) > .col-3-12")).click();
    // 111 | click | css=.row:nth-child(7) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(4) > .col-9-12")).click();
    // 112 | click | css=.row:nth-child(8) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(5) > .col-3-12")).click();
    // 113 | click | css=.row:nth-child(8) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(5) > .col-9-12")).click();
    // 114 | click | css=.row:nth-child(9) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(6) > .col-3-12")).click();
    // 115 | click | css=.row:nth-child(9) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(6) > .col-9-12")).click();
    // 116 | click | css=.row:nth-child(10) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(7) > .col-3-12")).click();
    // 117 | click | css=.row:nth-child(10) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(7) > .col-9-12")).click();
    // 118 | click | css=.row:nth-child(11) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(8) > .col-3-12")).click();
    // 119 | click | css=.row:nth-child(11) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(8) > .col-9-12")).click();
    // 120 | click | css=.row:nth-child(12) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(9) > .col-3-12")).click();
    // 121 | click | css=.row:nth-child(12) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(9) > .col-9-12")).click();
    // 122 | click | css=.row:nth-child(12) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(10) > .col-3-12")).click();
    // 123 | click | css=.row:nth-child(13) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(10) > .col-9-12")).click();
    // 124 | click | css=.row:nth-child(13) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(11) > .col-3-12")).click();
    // 125 | click | css=.row:nth-child(14) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(11) > .col-9-12")).click();
    // 126 | click | css=.row:nth-child(14) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(12) > .col-3-12")).click();
    // 127 | click | css=.row:nth-child(15) > .col-3-12 |
    await driver.findElement(By.css(".row:nth-child(12) > .col-9-12")).click();
    // 128 | click | css=.row:nth-child(15) > .col-9-12 |
    await driver.findElement(By.css(".row:nth-child(12) > .col-3-12")).click();
    // 129 | click | css=.\_4aGEkW |
    await driver.findElement(By.css(".row:nth-child(13) > .col-9-12")).click();
    // 130 | click | css=.\_4aGEkW |
    await driver.findElement(By.css(".row:nth-child(13) > .col-9-12")).click();
    // 131 | click | css=.\_4aGEkW |
    await driver.findElement(By.css(".row:nth-child(14) > .col-3-12")).click();
    // 132 | click | css=.t7DWYS |
    await driver.findElement(By.css(".row:nth-child(14) > .col-9-12")).click();
    // 133 | click | css=.ELSIVL:nth-child(2) > .Ez0xjR |
    await driver.findElement(By.css(".row:nth-child(15) > .col-3-12")).click();
    // 134 | click | css=.ELSIVL:nth-child(2) > .xe2C75 |
    await driver.findElement(By.css(".row:nth-child(15) > .col-9-12")).click();
    // 135 | click | css=.ELSIVL:nth-child(2) > .Ez0xjR |
    await driver.findElement(By.css(".\\_4aGEkW")).click();
    // 136 | click | css=.ELSIVL:nth-child(2) > .xe2C75 |
    await driver.findElement(By.css(".\\_4aGEkW")).click();
    // 137 | click | css=.gtm1So |
    await driver.findElement(By.css(".\\_4aGEkW")).click();
    // 138 | runScript | window.scrollTo(0,2756.5) |
    await driver.findElement(By.css(".t7DWYS")).click();
    // 139 | runScript | window.scrollTo(0,3661.5) |
    await driver.findElement(By.css(".ELSIVL:nth-child(2) > .Ez0xjR")).click();
    // 140 | click | css=.Ip5wZF:nth-child(1) .KlsEL9 |
    await driver.findElement(By.css(".ELSIVL:nth-child(2) > .xe2C75")).click();
    // 141 | click | linkText=Boston-01 Chunky Sneakers,Loafers,Walking Shoes Sneakers For Men |
    await driver.findElement(By.css(".ELSIVL:nth-child(2) > .Ez0xjR")).click();
    // 142 | selectWindow | handle=${win7204} |
    await driver.findElement(By.css(".ELSIVL:nth-child(2) > .xe2C75")).click();
    // 143 | runScript | window.scrollTo(0,0) |
    await driver.findElement(By.css(".gtm1So")).click();
    // 144 | close |  |
    await driver.executeScript("window.scrollTo(0,2756.5)");
    // 145 | selectWindow | handle=${win8163} |
    await driver.executeScript("window.scrollTo(0,3661.5)");
    // 146 | close |  |
    await driver.findElement(By.css(".Ip5wZF:nth-child(1) .KlsEL9")).click();
    // 147 | selectWindow | handle=${root} |
    vars["windowHandles"] = await driver.getAllWindowHandles();
    // 148 | runScript | window.scrollTo(0,0) |
    await driver
      .findElement(
        By.linkText(
          "Boston-01 Chunky Sneakers,Loafers,Walking Shoes Sneakers For Men"
        )
      )
      .click();
    vars["win7204"] = await waitForWindow(2000);
    await driver.switchTo().window(vars["win7204"]);
    await driver.executeScript("window.scrollTo(0,0)");
    await driver.close();
    await driver.switchTo().window(vars["win8163"]);
    await driver.close();
    await driver.switchTo().window(vars["root"]);
    await driver.executeScript("window.scrollTo(0,0)");
  });
});
