name: Sentiment Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sentiment-analysis:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Sentiment Analysis Library
        run: pip install textblob

      - name: Analyze Commit Messages
        run: |
          git log -1 --pretty=%B > commit_message.txt
          python -c "import textblob with open('commit_message.txt', 'r') as file: commit_message = file.read()    analysis = textblob.TextBlob(commit_message) print(f'Sentiment: {analysis.sentiment}')"
