name: Sentiment Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sentiment-analysis:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Python Installation
        run: |
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            if ! command -v python3 &> /dev/null; then
              echo "Python is not installed. Installing Python on Ubuntu..."
              sudo apt-get update
              sudo apt-get install python3.8
            else
              echo "Python is already installed on Ubuntu."
            fi
          elif [[ "$OSTYPE" == "darwin"* ]]; then
            if ! command -v python3 &> /dev/null; then
              echo "Python is not installed. Installing Python on macOS..."
              brew update
              brew install python@3.8
            else
              echo "Python is already installed on macOS."
            fi
          elif [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
            if ! command -v python3 &> /dev/null; then
              echo "Python is not installed. Installing Python on Windows..."
              choco install python --version=3.8
            else
              echo "Python is already installed on Windows."
            fi
          else
            echo "Unsupported OS type: $OSTYPE"
          fi

      - name: Install Sentiment Analysis Library
        run: |
          if ! pip show textblob > /dev/null 2>&1; then
            pip install textblob
          fi

      - name: Analyze Commit Messages
        run: |
          git log -1 --pretty=%B > commit_message.txt
          python analyze_commit.py
